const CAR_DATABASE = {
  1: {
    id:           1,
    name:         'Toyota Corolla 2021',
    image:        'images/car-1.jpg',
    type:         'Sedan',
    price:        550,
    location:     'Johannesburg',
    city:         'Johannesburg, ZA',
    transmission: 'Automatic',
    year:         2021,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'Air Con'],
    rating:       4.8,
    reviews:      24,
    grad:         'grad-1',
    kmPerDay:     '250km / day included',
    fuelNote:     'Unleaded 95',
    host: {
      name:     'Thandi M.',
      since:    2022,
      trips:    87,
      response: '100%',
      time:     '< 1hr',
      rating:   '4.9/5',
    },
  },
  2: {
    id:           2,
    name:         'Kia Sorento 2023',
    image:        'images/car-2.jpg',
    type:         'SUV',
    price:        950,
    location:     'Cape Town',
    city:         'Cape Town, ZA',
    transmission: 'Automatic',
    year:         2023,
    fuel:         'Petrol',
    seats:        7,
    features:     ['7 Seats', 'Petrol', 'Air Con'],
    rating:       4.9,
    reviews:      41,
    grad:         'grad-2',
    kmPerDay:     '300km / day included',
    fuelNote:     'Unleaded 95',
    host: {
      name:     'Sipho N.',
      since:    2021,
      trips:    132,
      response: '98%',
      time:     '< 2hrs',
      rating:   '4.8/5',
    },
  },
  3: {
    id:           3,
    name:         'VW Polo 2020',
    image:        'images/car-3.jpg',
    type:         'Hatchback',
    price:        420,
    location:     'Pretoria',
    city:         'Pretoria, ZA',
    transmission: 'Manual',
    year:         2020,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'Bluetooth'],
    rating:       4.7,
    reviews:      18,
    grad:         'grad-3',
    kmPerDay:     '200km / day included',
    fuelNote:     'Unleaded 93',
    host: {
      name:     'Ayanda D.',
      since:    2020,
      trips:    64,
      response: '95%',
      time:     '< 3hrs',
      rating:   '4.7/5',
    },
  },
  4: {
    id:           4,
    name:         'Ford Ranger 2022',
    image:        'images/car-4.jpg',
    type:         'Bakkie',
    price:        780,
    location:     'Durban',
    city:         'Durban, ZA',
    transmission: 'Automatic',
    year:         2022,
    fuel:         'Diesel',
    seats:        5,
    features:     ['5 Seats', 'Diesel', '4x4'],
    rating:       4.6,
    reviews:      33,
    grad:         'grad-4',
    kmPerDay:     '350km / day included',
    fuelNote:     'Diesel only',
    host: {
      name:     'Marcus T.',
      since:    2021,
      trips:    98,
      response: '92%',
      time:     '< 1hr',
      rating:   '4.6/5',
    },
  },
  5: {
    id:           5,
    name:         'BMW 320i 2021',
    image:        'images/car-5.jpg',
    type:         'Sedan',
    price:        680,
    location:     'Sandton',
    city:         'Sandton, ZA',
    transmission: 'Automatic',
    year:         2021,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'Sunroof'],
    rating:       5.0,
    reviews:      12,
    grad:         'grad-5',
    kmPerDay:     '200km / day included',
    fuelNote:     'Premium Unleaded 95',
    host: {
      name:     'Elena R.',
      since:    2022,
      trips:    45,
      response: '100%',
      time:     '< 1hr',
      rating:   '5.0/5',
    },
  },
  6: {
    id:           6,
    name:         'Hyundai i20 2019',
    image:        'images/car-6.jpg',
    type:         'Hatchback',
    price:        390,
    location:     'Johannesburg',
    city:         'Johannesburg, ZA',
    transmission: 'Manual',
    year:         2019,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'USB Port'],
    rating:       4.5,
    reviews:      29,
    grad:         'grad-6',
    kmPerDay:     '200km / day included',
    fuelNote:     'Unleaded 93',
    host: {
      name:     'Priya S.',
      since:    2020,
      trips:    76,
      response: '97%',
      time:     '< 2hrs',
      rating:   '4.5/5',
    },
  },
  7: {
    id:           7,
    name:         'Toyota Fortuner 2022',
    image:        'images/car-7.jpg',
    type:         'SUV',
    price:        1100,
    location:     'Cape Town',
    city:         'Cape Town, ZA',
    transmission: 'Automatic',
    year:         2022,
    fuel:         'Diesel',
    seats:        7,
    features:     ['7 Seats', 'Diesel', '4x4'],
    rating:       4.8,
    reviews:      55,
    grad:         'grad-7',
    kmPerDay:     '400km / day included',
    fuelNote:     'Diesel only',
    host: {
      name:     'Liam O.',
      since:    2019,
      trips:    210,
      response: '99%',
      time:     '< 1hr',
      rating:   '4.9/5',
    },
  },
  8: {
    id:           8,
    name:         'Toyota HiAce 2020',
    image:        'images/car-8.jpg',
    type:         'Minivan',
    price:        720,
    location:     'Pretoria',
    city:         'Pretoria, ZA',
    transmission: 'Manual',
    year:         2020,
    fuel:         'Diesel',
    seats:        14,
    features:     ['14 Seats', 'Diesel', 'Large Boot'],
    rating:       4.4,
    reviews:      37,
    grad:         'grad-8',
    kmPerDay:     '300km / day included',
    fuelNote:     'Diesel only',
    host: {
      name:     'Jordan S.',
      since:    2020,
      trips:    119,
      response: '90%',
      time:     '< 3hrs',
      rating:   '4.4/5',
    },
  },
  9: {
    id:           9,
    name:         'Nissan Almera 2020',
    image:        'images/car-9.jpg',
    type:         'Sedan',
    price:        490,
    location:     'Durban',
    city:         'Durban, ZA',
    transmission: 'Automatic',
    year:         2020,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'Air Con'],
    rating:       4.6,
    reviews:      21,
    grad:         'grad-1',
    kmPerDay:     '250km / day included',
    fuelNote:     'Unleaded 93',
    host: {
      name:     'Thandi M.',
      since:    2022,
      trips:    87,
      response: '100%',
      time:     '< 1hr',
      rating:   '4.6/5',
    },
  },
  10: {
    id:           10,
    name:         'Isuzu D-Max 2023',
    image:        'images/car-10.jpg',
    type:         'Bakkie',
    price:        850,
    location:     'Sandton',
    city:         'Sandton, ZA',
    transmission: 'Automatic',
    year:         2023,
    fuel:         'Diesel',
    seats:        5,
    features:     ['5 Seats', 'Diesel', 'Canopy'],
    rating:       4.7,
    reviews:      16,
    grad:         'grad-4',
    kmPerDay:     '350km / day included',
    fuelNote:     'Diesel only',
    host: {
      name:     'Sipho N.',
      since:    2021,
      trips:    132,
      response: '98%',
      time:     '< 1hr',
      rating:   '4.7/5',
    },
  },
  11: {
    id:           11,
    name:         'Haval H6 2022',
    image:        'images/car-11.jpg',
    type:         'SUV',
    price:        880,
    location:     'Johannesburg',
    city:         'Johannesburg, ZA',
    transmission: 'Automatic',
    year:         2022,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', '360 Cam'],
    rating:       4.5,
    reviews:      9,
    grad:         'grad-3',
    kmPerDay:     '250km / day included',
    fuelNote:     'Unleaded 95',
    host: {
      name:     'Ayanda D.',
      since:    2020,
      trips:    64,
      response: '95%',
      time:     '< 2hrs',
      rating:   '4.5/5',
    },
  },
  12: {
    id:           12,
    name:         'Renault Clio 2021',
    image:        'images/car-12.jpg',
    type:         'Hatchback',
    price:        450,
    location:     'Cape Town',
    city:         'Cape Town, ZA',
    transmission: 'Manual',
    year:         2021,
    fuel:         'Petrol',
    seats:        5,
    features:     ['5 Seats', 'Petrol', 'Apple CarPlay'],
    rating:       4.8,
    reviews:      14,
    grad:         'grad-6',
    kmPerDay:     '200km / day included',
    fuelNote:     'Unleaded 93',
    host: {
      name:     'Marcus T.',
      since:    2021,
      trips:    98,
      response: '92%',
      time:     '< 2hrs',
      rating:   '4.8/5',
    },
  },
};

